mod buildinfo {
    // include file generated by buildinfo.rs
    include!(concat!(env!("OUT_DIR"), "/buildinfo_gen.rs"));
}

use clap::Args;

#[derive(Debug, Args)]
pub struct Param { }


pub fn run(_param: Param) -> () {
    println!("built with {} at {}", buildinfo::BUILD_RUSTC, buildinfo::BUILD_DATETIME);
}
